add_test( checkRotateTest.CheckRoateTest /Users/franky/documents/github/wyy/bin/Debug/log_test [==[--gtest_filter=checkRotateTest.CheckRoateTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( checkRotateTest.CheckRoateTest PROPERTIES WORKING_DIRECTORY /Users/franky/documents/github/wyy/unitest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( testEnableTest.CheckEnableTest /Users/franky/documents/github/wyy/bin/Debug/log_test [==[--gtest_filter=testEnableTest.CheckEnableTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( testEnableTest.CheckEnableTest PROPERTIES WORKING_DIRECTORY /Users/franky/documents/github/wyy/unitest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( log_test_TESTS checkRotateTest.CheckRoateTest testEnableTest.CheckEnableTest)
