# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/GoogleTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.22/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/franky/documents/github/wyy/unitest/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestTargets-noconfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/lib/cmake/GTest/GTestTargets.cmake))

/Users/franky/documents/github/wyy/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/franky/documents/github/wyy -B/Users/franky/documents/github/wyy
