# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/franky/documents/github/wyy/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/franky/documents/github/wyy/src/obclient/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/franky/documents/github/wyy/src/observer/CMakeLists.txt))

/Users/franky/documents/github/wyy/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/franky/documents/github/wyy -B/Users/franky/documents/github/wyy
